camel:
  springboot:
    name: Conduit Backend Camel implementation
    startup-summary-level: verbose

    routes-include-pattern: classpath:camel/**/*.xml

  servlet:
    mapping:
      contextPath: /api/*

  rest:
    inline-routes: false

spring:

  datasource:
    url: jdbc:h2:file:./data/conduit.h2;AUTO_SERVER=TRUE

  jpa:
    database: h2
    hibernate:
      ddl-auto: update



management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      github:
        jacekszymanski: TRACE
