/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.jacekszymanski.realcamel.api;

import com.github.jacekszymanski.realcamel.model.GetProfileByUsername200Response;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.stereotype.Component;
import com.github.jacekszymanski.realcamel.model.*;

@Component
public class ProfileApi extends RouteBuilder {

    @Override
    public void configure() throws Exception {


        /**
        POST /profiles/{username}/follow : Follow a user
        **/
        rest()
            .securityDefinitions()
                .apiKey("Token")
                    .withHeader("Token")

            .endSecurityDefinition()
            .post("/profiles/{username}/follow")
                .description("Follow a user")
                .id("followUserByUsernameApi")
                .produces("application/json")
                .outType(GetProfileByUsername200Response.class)
                .param()
                    .name("username")
                    .type(RestParamType.path)
                    .required(true)
                    .description("Username of the profile you want to follow")
                .endParam()
                .to("direct:followUserByUsername");


        /**
        GET /profiles/{username} : Get a profile
        **/
        rest()
            .get("/profiles/{username}")
                .description("Get a profile")
                .id("getProfileByUsernameApi")
                .produces("application/json")
                .outType(GetProfileByUsername200Response.class)
                .param()
                    .name("username")
                    .type(RestParamType.path)
                    .required(true)
                    .description("Username of the profile to get")
                .endParam()
                .to("direct:getProfileByUsername");


        /**
        DELETE /profiles/{username}/follow : Unfollow a user
        **/
        rest()
            .securityDefinitions()
                .apiKey("Token")
                    .withHeader("Token")

            .endSecurityDefinition()
            .delete("/profiles/{username}/follow")
                .description("Unfollow a user")
                .id("unfollowUserByUsernameApi")
                .produces("application/json")
                .outType(GetProfileByUsername200Response.class)
                .param()
                    .name("username")
                    .type(RestParamType.path)
                    .required(true)
                    .description("Username of the profile you want to unfollow")
                .endParam()
                .to("direct:unfollowUserByUsername");

    }
}
