/**
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.github.jacekszymanski.realcamel.api;

import com.github.jacekszymanski.realcamel.model.GetTags200Response;
import org.apache.camel.builder.RouteBuilder;
import org.springframework.stereotype.Component;
import com.github.jacekszymanski.realcamel.model.*;

@Component
public class TagsApi extends RouteBuilder {

    @Override
    public void configure() throws Exception {


        /**
        GET /tags : Get tags
        **/
        rest()
            .get("/tags")
                .description("Get tags")
                .id("getTagsApi")
                .produces("application/json")
                .outType(GetTags200Response.class)
                .to("direct:getTags");

    }
}
